### ISSUE TITLE
Create NextJs App

### ISSUE THREAD

**Issue by ZU3AIRE** [Aftabsattar/email-sender#1]
### First Issue
Please create initial next app and push in the a new branch

```bash
# command for new project
npx create-next-app email-sender  

# command for running the project
npm run dev
```

Please push the project and add a comment here

**Comment by Aftabsattar** [comment]
I have complete our task.

**Comment by ZU3AIRE** [comment]
You pushed the code into the main (wrong branch). Please check and verify here so we can correct this

**Comment by Aftabsattar** [comment]
Done my task

**Comment by ZU3AIRE** [comment]
Please create new branch from the issue and push new next js app in it 
Also please remove the code from main
